---
- name: Create Airsonic Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ airsonic_data_directory }}/data"
    - "{{ airsonic_data_directory }}/playlists"

- name: Airsonic Docker Stack
  docker_stack:
    state: present
    name: airsonic
    compose:
    -   version: '3'
        services:
          airsonic:
            image: airsonic/airsonic:latest
            volumes:
              - "{{ airsonic_data_directory }}/data:/airsonic/data:rw"
              - "{{ airsonic_data_directory }}/playlists:/airsonic/playlists:rw"
              - "{{ samba_shares_root }}/music:/airsonic/music:rw"
              - "{{ samba_shares_root }}/podcasts:/airsonic/podcasts:rw"
            ports:
              - "4040:4040"
            labels:
              traefik.backend: "airsonic"
              traefik.frontend.rule: "Host:airsonic.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "4040"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"

