- name: Cloudflare Dynamic DNS Stack
  docker_stack:
    state: present
    name: cloudflare-ddns
    compose:
    -   version: '3'
        services:
          cloudflare-ddns:
            image: joshava/cloudflare-ddns:latest
            environment:
              ZONE: "{{ cloudflare_zone }}"
              HOST: "{{ cloudflare_host }}"
              EMAIL: "{{ cloudflare_email }}"
              API: "{{ cloudflare_api_key }}"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "512MB"

