---
- name: Create Couchpotato Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ docker_home }}/couchpotato/config"

- name: Couchpotato Docker Stack
  docker_stack:
    state: present
    name: couchpotato
    compose:
    -   version: '3'
        services:
          couchpotato:
            image: linuxserver/couchpotato
            volumes:
              - "{{ couchpotato_config_directory }}:/config:rw"
              - "{{ couchpotato_downloads_directory }}/completed:/downloads:rw"
              - "{{ couchpotato_movies_directory }}:/movies:rw"
              - "{{ couchpotato_torrents_directory }}:/torrents:rw"
            ports:
              - "5050:5050"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ couchpotato_user_id }}"
              PGID: "{{ couchpotato_group_id }}"
            labels:
              traefik.backend: "couchpotato"
              traefik.frontend.rule: "Host:couchpotato.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "5050"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"