---
- name: Create Duplicati Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ duplicati_data_directory }}"

- name: Dupicati Docker Container
  docker_stack:
    state: present
    name: duplicati
    compose:
    -   version: '3'
        services:
          duplicati:
            image: linuxserver/duplicati
            volumes:
              - "{{ duplicati_data_directory }}:/config:rw"
              - "{{ samba_shares_root }}:/source/shares:ro"
              - "{{ docker_home }}:/source/docker:ro"
              - "/etc/timezone:/etc/timezone:ro"
            ports:
              - "8200:8200"
            labels:
              traefik.backend: "duplicati"
              traefik.frontend.rule: "Host:duplicati.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "8200"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
