- name: Create Emby Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ emby_config_directory }}"

- name: emby Docker Container
  docker_stack:
    state: present
    name: emby
    compose:
    -   version: '3'
        services:
          portainer:
            image: emby/embyserver
            volumes:
              - "{{ emby_config_directory }}:/config:rw"
              - "{{ emby_movies_directory }}:/movies:rw"
              - "{{ emby_tv_directory }}:/tv:rw"
            ports:
              - "8096:8096" # HTTP port
              - "8920:8920" # HTTPS port
            #network_mode: host
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ couchpotato_user_id }}"
              PGID: "{{ couchpotato_group_id }}"
            labels:
              traefik.backend: "emby"
              traefik.frontend.rule: "Host:emby.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "5050"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
