- name: Create get_iplayer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ get_iplayer_config_directory }}"
    - "{{ get_iplayer_download_directory }}"

- name: get_iplayer Docker Stack
  docker_stack:
    state: present
    name: get_iplayer
    compose:
    -   version: '3'
        services:
          get_iplayer:
            image: kolonuk/get_iplayer
            volumes:
              - "{{ get_iplayer_config_directory }}:/root/.get_iplayer:rw"
              - "{{ get_iplayer_download_directory }}:/root/output:rw"
            ports:
              - "8182:8182"
            labels:
              traefik.backend: "get_iplayer"
              traefik.frontend.rule: "Host:get_iplayer.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "8182"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
