---
- name: Create Gitea group account
  group:
    name: git
    gid: 1309
    state: present

- name: Create Gitea user account
  user:
    name: git
    uid: 1309
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: git

- name: Create Gitea Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    recurse: yes
  with_items:
    - "{{ gitea_data_directory }}/gitea"
    - "{{ gitea_data_directory }}/mysql"

- name: Gitea Docker Stack
  docker_stack:
    state: present
    name: gitea
    compose:
    -   version: '3'
        services:
          gitea:
            image: gitea/gitea:1.6
            volumes:
              - "{{ gitea_data_directory }}/gitea:/data:rw"
            ports:
              - "3001:3000"
              - "222:22"
            environment:
              DB_TYPE: mysql
              DB_HOST: db:3306
              DB_NAME: gitea
              DB_USER: gitea
              DB_PASSWD: gitea
              RUN_MODE: prod
              SSH_DOMAIN: "{{ ansible_nas_hostname }}"
              SSH_PORT: 222
              ROOT_URL: "http://{{ ansible_nas_hostname }}:3001/"
              USER_UID: 1309
              USER_GID: 1309
            labels:
              traefik.backend: "gitea"
              traefik.frontend.rule: "Host:gitea.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "3000"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
          db:
            image: mysql:5.7
            volumes:
              - "{{ gitea_data_directory }}/mysql:/var/lib/mysql:rw"
            environment:
              MYSQL_DATABASE: gitea
              MYSQL_USER: gitea
              MYSQL_PASSWORD: gitea
              MYSQL_ROOT_PASSWORD: gitea
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
