- name: Glances Docker Stack
  docker_stack:
    state: present
    name: glances
    compose:
    -   version: '3'
        services:
          glances:
            image: nicolargo/glances
            volumes:
              #- "/glances.conf:/glances/conf/glances.conf"
              - "/var/run/docker.sock:/var/run/docker.sock:ro"
              - "/etc/timezone:/etc/timezone:ro"
            ports:
              - "61208:61208"
              - "61209:61209"
            #pid_mode: host
            #network_mode: host
            environment:
              GLANCES_OPT: "-w"
            labels:
              traefik.backend: "glances"
              traefik.frontend.rule: "Host:glances.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "61208"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
