---
- name: Create Guacamole directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ guacamole_data_directory }}/mysql"

- name: Copy Guacamole database init script
  copy:
    src: files/guacamole/initdb-0.9.14.sql
    dest: "{{ guacamole_data_directory }}/initdb-0.9.14.sql"

- name: Guacamole Docker Stack
  docker_stack:
    state: present
    name: guacamole
    compose:
    -   version: '3'
        services:
          guacamole:
            image: "{{ guacamole_docker_image }}"
            ports:
              - "8090:8080"
            environment:
              MYSQL_DATABASE: guacamole
              MYSQL_USER: guacamole-user
              MYSQL_PASSWORD: guacamole-pass
            labels:
              traefik.backend: "guacamole"
              traefik.frontend.rule: "Host:guacamole.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "8080"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
          guacd:
            image: "{{ guacamole_guacd_docker_image }}"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
          db:
            image: mysql:5.7
            volumes:
              - "{{ guacamole_data_directory }}/mysql:/var/lib/mysql:rw"
              - "{{ guacamole_data_directory }}/initdb-0.9.14.sql:/docker-entrypoint-initdb.d/initdb-0.9.14.sql:ro"
            environment:
              MYSQL_DATABASE: guacamole
              MYSQL_USER: guacamole-user
              MYSQL_PASSWORD: guacamole-pass
              MYSQL_ROOT_PASSWORD: guacamole-secret
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"