---
- name: Create Heimdall group
  group:
    name: heimdall
    gid: 1310
    state: present

- name: Create Heimdall user
  user:
    name: heimdall
    uid: 1310
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: heimdall

- name: Create Heimdall Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: heimdall
    group: heimdall
  with_items:
    - "{{ heimdall_data_directory }}"

- name: Heimdall Docker Stack
  docker_stack:
    state: present
    name: heimdall
    compose:
    -   version: '3'
        services:
          heimdall:
            image: "{{ heimdall_docker_image }}"
            volumes:
              - "{{ heimdall_data_directory }}:/config:rw"
            ports:
              - "10080:80"
              - "10443:443"
            environment:
              PUID: 1310
              PGID: 1310
              TZ: "{{ ansible_nas_timezone }}"
            labels:
              traefik.backend: "heimdall"
              traefik.frontend.rule: "Host:heimdall.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "80"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
