---
- name: Create jackett Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ jackett_data_directory }}"

- name: Jackett Docker Stack
  docker_stack:
    state: present
    name: jackett
    compose:
    -   version: '3'
        services:
          jackett:
            image: linuxserver/jackett
            volumes:
              - "{{ jackett_data_directory }}:/config:rw"
              - "/etc/localtime:/etc/localtime:ro"
              - "{{ torrents_root }}:/downloads"
            ports:
              - "9117:9117"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
            labels:
              traefik.backend: "jackett"
              traefik.frontend.rule: "Host:jackett.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "9117"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"