###### Create
- name: Get docker group id
  group:
    name: docker
  register: docker_group

- name: Netdata Docker Container
  docker_stack:
    state: present
    name: netdata
    compose:
    -   version: '3'
        services:
          netdata:
            image: netdata/netdata
            hostname: "{{ ansible_nas_hostname }}.{{ ansible_nas_domain }}"
            ports:
              - "19999:19999"
            security_opt:
              - apparmor:unconfined
            cap_add:
              - SYS_PTRACE
            volumes:
              - "/proc:/host/proc:ro"
              - "/sys:/host/sys:ro"
              - "/var/run/docker.sock:/var/run/docker.sock:ro"
            environment:
              PGID: "{{ docker_group.gid }}"
            labels:
              traefik.backend: "netdata"
              traefik.frontend.rule: "Host:netdata.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "19999"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
          db:
            image: postgres:11.1
            volumes:
              - "{{ miniflux_data_directory }}/postgres:/var/lib/postgresql/data:rw"
            environment:
              POSTGRES_USER: miniflux
              POSTGRES_PASSWORD: supersecure
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
