---
- name: Create Nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nextcloud_data_directory }}/nextcloud"
    - "{{ nextcloud_data_directory }}/mysql"

- name: Nextcloud Docker Container
  docker_stack:
    state: present
    name: nextcloud
    compose:
    -   version: '3'
        services:
          nextcloud:
            image: nextcloud:14
            ports:
              - "8080:80"
            volumes:
              - "{{ nextcloud_data_directory }}/nextcloud:/var/www/html:rw"
            environment:
              MYSQL_HOST: db
              MYSQL_DATABASE: nextcloud
              MYSQL_USER: nextcloud-user
              MYSQL_PASSWORD: nextcloud-pass
            labels:
              traefik.backend: "nextcloud"
              traefik.frontend.rule: "Host:nextcloud.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "80"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
          db:
            image: mysql:5.7
            volumes:
              - "{{ nextcloud_data_directory }}/mysql:/var/lib/mysql:rw"
            environment:
              MYSQL_DATABASE: nextcloud
              MYSQL_USER: nextcloud-user
              MYSQL_PASSWORD: nextcloud-pass
              MYSQL_ROOT_PASSWORD: nextcloud-secret
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"