- name: Create Plex Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ plex_config_directory }}"


- name: Plex Docker Stack
  docker_stack:
    state: present
    name: plex
    compose:
    -   version: '3'
        services:
          plex:
            image: linuxserver/plex
            volumes:
              - "{{ plex_config_directory }}:/config:rw"
              - "{{ plex_movies_directory }}:/movies:rw"
              - "{{ plex_tv_directory }}:/tv:rw"
            network_mode: "host"
            ports:
              - "8203:8201"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ plex_user_id }}"
              PGID: "{{ plex_group_id }}"
            labels:
              traefik.backend: "plex"
              traefik.frontend.rule: "Host:plex.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "8203"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
