---
- name: Create Radarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ radarr_data_directory }}"

- name: Radarr Docker Stack
  docker_stack:
    state: present
    name: radarr
    compose:
    -   version: '3'
        services:
          radarr:
            image: linuxserver/radarr
            volumes:
              - "{{ radarr_movies_directory }}:/movies:rw"
              - "{{ radarr_download_directory }}/downloads:/downloads:rw"
              - "{{ radarr_data_directory }}:/config:rw"
            ports:
              - "7878:7878"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ radarr_user_id }}"
              PGID: "{{ radarr_group_id }}"
            labels:
              traefik.backend: "radarr"
              traefik.frontend.rule: "Host:radarr.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "7878"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"