---
- name: Create Sickrage Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ sickrage_config_directory }}"

- name: Sickrage Docker Stack
  docker_stack:
    state: present
    name: sickrage
    compose:
    -   version: '3'
        services:
          sickrage:
            image: linuxserver/sickrage
            volumes:
              - "{{ sickrage_config_directory }}:/config:rw"
              - "{{ sickrage_downloads_directory }}/completed:/downloads:rw"
              - "{{ sickrage_tv_directory }}:/tv:rw"
            ports:
              - "8081:8081"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ sickrage_user_id }}"
              PGID: "{{ sickrage_group_id }}"
            labels:
              traefik.backend: "sickrage"
              traefik.frontend.rule: "Host:sickrage.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "8081"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"