---
- name: Create Sonarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sonarr_data_directory }}"

- name: Sonarr Docker Stack
  docker_stack:
    state: present
    name: sonarr
    compose:
    -   version: '3'
        services:
          sonarr:
            image: linuxserver/sonarr
            volumes:
              - "{{ sonarr_tv_directory }}:/tv:rw"
              - "{{ sonarr_download_directory }}/complete:/downloads:rw"
              - "{{ sonarr_data_directory }}:/config:rw"
            ports:
              - "8989:8989"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ sonarr_user_id }}"
              PGID: "{{ sonarr_group_id }}"
            labels:
              traefik.backend: "sonarr"
              traefik.frontend.rule: "Host:sonarr.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "8989"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"