- name: Create Tautulli Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ tautulli_config_directory }}"

- name: Tautulli Docker Stack
  docker_stack:
    state: present
    name: tautulli
    compose:
    -   version: '3'
        services:
          tautulli:
            image: linuxserver/tautulli
            volumes:
              - "{{ tautulli_config_directory }}:/config:rw"
            # network_mode: "host"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ tautulli_user_id }}"
              PGID: "{{ tautulli_group_id }}"
            labels:
              traefik.backend: "tautulli"
              traefik.frontend.rule: "Host:tautulli.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "80"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"