---
- name: Time Machine Directories
  file:
    path: "{{ timemachine_data_directory }}"
    state: directory

- name: Time Machine Docker Stack
  docker_stack:
    state: present
    name: timemachine
    compose:
    -   version: '3'
        services:
          timemachine:
            image: mbentley/timemachine:latest
            volumes:
              - "{{ timemachine_data_directory }}/data:/opt/timemachine"
              - "{{ timemachine_data_directory }}/logs:/var/log/supervisor"
              - "/var/run/dbus:/var/run/dbus"
            ports:
              - "548:548"
            # network_mode: "host"
            environment:
              VOLUME_SIZE_LIMIT: "{{ timemachine_volume_size_limit }}"
              PASSWORD: "{{ timemachine_password }}"
              SHARE_NAME: "{{ timemachine_share_name }}"
              LOG_LEVEL: "{{ timemachine_log_level }}"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
