---
- name: Ensure Nginx Docker Container is absent
  docker_container:
    name: nginx-proxy
    state: absent

- name: Nginx Letsencrypt Container is absent
  docker_container:
    name: letsencrypt-nginx-proxy-companion
    state: absent

- name: Create Trafik Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_data_directory }}"

- name: Template Traefik config.toml
  template:
    src: traefik/traefik.toml
    dest: "{{ traefik_data_directory }}/traefik.toml"


- name: Traefik Docker Stack
  docker_stack:
    state: traefik
    name: traefik
    compose:
    -   version: '3'
        services:
          traefik:
            image: "{{ traefik_docker_image }}"
            volumes:
              - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
              - "/var/run/docker.sock:/var/run/docker.sock:ro"
            ports:
              - "80:80"
              - "443:443"
              - "8083:8083"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"