---
- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission_config_directory }}"
    - "{{ transmission_download_directory }}"
    - "{{ transmission_watch_directory }}"


- name: Transmission Docker Stack
  docker_stack:
    state: present
    name: transmission
    compose:
    -   version: '3'
        services:
          transmission:
            image: linuxserver/transmission
            volumes:
              - "{{ transmission_config_directory }}:/config:rw"
              - "{{ transmission_download_directory }}:/downloads:rw"
              - "{{ transmission_watch_directory }}:/watch:rw"
            ports:
              - "9091:9091"
              - "51413:51413"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
              PUID: "{{ transmission_user_id }}"
              PGID: "{{ transmission_group_id }}"
            devices:
              - /dev/net/tun
            cap_add:
              - NET_ADMIN
            labels:
              traefik.backend: "transmission"
              traefik.frontend.rule: "Host:transmission.{{ ansible_nas_domain }}"
              traefik.enable: "true"
              traefik.port: "9091"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"

