---
- include_vars: group_vars/vpn_credentials.yml

- name: Create NordVPN Config Directory
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ openvpn_config_directory }}/nordvpn"

- name: Download latest NordVPN configs
  unarchive:
    src: https://nordvpn.com/api/files/zip
    dest: "{{ openvpn_config_directory }}/nordvpn"
    remote_src: True

- name: Replace NordVPN configs with credential file
  shell: 'sed -i "s/auth-user-pass/auth-user-pass \/config\/openvpn-credentials.txt/" {{ openvpn_config_directory }}/nordvpn/*.ovpn'

- name: VPN Docker Stack
  docker_stack:
    state: present
    name: openvpn-client
    compose:
    -   version: '3'
        services:
          openvpn-client:
            image: dceschmidt/openvpn-client
            volumes:
              "{{ openvpn_config_directory }}/nordvpn:/etc/openvpn/conf/nordvpn:rw"
            ports:
              - "548:548"
            # network_mode: "host"
            devices:
              - /dev/net/tun
            capabilities:
              - NET_ADMIN
            environment:
              OPENVPN_PROVIDER: "{{ openvpn_provider }}"
              OPENVPN_USERNAME: "{{ openvpn_username }}"
              OPENVPN_PASSWORD: "{{ openvpn_password }}"
              OPENVPN_CONFIG: "{{ openvpn_config }}"
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"
