---

- name: Watchtower Docker Stack
  docker_stack:
    state: present
    name: watchtower
    compose:
    -   version: '3'
        services:
          watchtower:
            image: v2tec/watchtower
            volumes:
              - "{{ transmission_config_directory }}:/config:rw"
              - "{{ transmission_download_directory }}:/downloads:rw"
              - "{{ transmission_watch_directory }}:/watch:rw"
            environment:
              TZ: "{{ ansible_nas_timezone }}"
            command: "{{ watchtower_command }}"  
            deploy:
              restart_policy:
                condition: on-failure
              resources:
                limits:
                  memory: "1g"